name: Validate JSON Schema

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate JSON file
        uses: python-jsonschema/check-jsonschema@0.36.1
        with:
          files: 'resources/cli-options.json'
          schema: 'resources/cli-options.schema.json'
